package com.padacn.xmgoing.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.padacn.xmgoing.bean.HotSearch;

import com.padacn.xmgoing.dao.HotSearchDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig hotSearchDaoConfig;

    private final HotSearchDao hotSearchDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        hotSearchDaoConfig = daoConfigMap.get(HotSearchDao.class).clone();
        hotSearchDaoConfig.initIdentityScope(type);

        hotSearchDao = new HotSearchDao(hotSearchDaoConfig, this);

        registerDao(HotSearch.class, hotSearchDao);
    }
    
    public void clear() {
        hotSearchDaoConfig.clearIdentityScope();
    }

    public HotSearchDao getHotSearchDao() {
        return hotSearchDao;
    }

}
